# Форматы чатов (можно создавать свои). Поддерживается PlaceholderAPI
# Плейсхолдеры плагина:
# %player% - ник игрока
# %prefix% - префикс игрока (берётся из Vault API)
# %suffix% - суффикс игрока (берётся из Vault API)
# %dph% - плейсхолдер группы
# %message% - сообщение игрока
chatFormats:
  local:
    format: "&aⓁ&f %prefix% &8⋆&f %player%&7:%dph% %message%"
    radius: 100
    # Если префикс указан пустым - канал становится дефолтным
    prefix: ''
    # Кулдаун для чата в миллисекундах
    cooldown: 500
    # Право на канал (для отправки и просмотра сообщений)
    # Если канал дефолтный - право не требуется.
    # Если не указано - используется формат pchat.channel.<имя_из_конфига>
    permission: pchat.channel.local

  global:
    format: "&cⒼ&f %prefix% &8⋆&f %player%&7:%dph% %message%"
    # Будет виден всем игрокам, если указано -1
    radius: -1
    # Если указан дубликат префикса - будет использоваться последний канал из конфига с таким префиксом
    prefix: '!'
    cooldown: 1500

  # Сообщение о кулдауне (может быть применено отдельно к каналу)
  cooldownMessage: "&e[♻]&f Вы пишете слишком быстро! Подождите ещё %time%"

  # Ховер-текст (может быть применён отдельно к каналу)
  # При включении заменяет стандартную логику чата, что может повлиять на работу других плагинов с форматированием.
  # Сообщения будут отправляться от имени сервера.
  hoverText:
    enable: false
    format: |-
      &fИнформация об игроке %player%
      &fРанг: &6%vault_group%
      &fХП: &6%player_health%
      &fОпыт: &6%player_exp%
    # Настройка click-события (действие при клике на сообщение игрока)
    clickEvent:
      enable: false
      actionType: SUGGEST_COMMAND
      actionValue: "/msg %player%"

  # Плейсхолдеры для донатов по группам (могут применяться отдельно к каналу)
  donatePlaceholders:
    default: "&7"
    admin: "&f&l"

  # Приоритет слушателя чата
  # https://jd.papermc.io/paper/1.21.11/org/bukkit/event/EventPriority.html
  chatPriority: LOW

  # Пересылать ли сообщения между серверами в одной сети
  # (на данный момент доступно только для глобального чата)
  proxy: false

# Настройка блокировки чата для новичков
newbieChat:
  # Включён ли newbieChat
  enable: true
  # Кулдаун на чат для новичков в секундах
  newbieCooldown: 600
  # Сообщение для новичков при попытке написать в чат
  newbieChatMessage: "&c[★] &6Подождите! Чтобы писать в чат, необходимо отыграть 10 минут на сервере. Осталось: &c%time%"
  # Сообщение при попытке использовать команды
  newbieCommandMessage: "&c[★] &6Подождите! Чтобы использовать эту команду, необходимо отыграть 10 минут на сервере. Осталось: &c%time%"
  # Команды, попадающие под ограничение newbieChat
  newbieCommands:
    - "/m"
    - "/pm"
    - "/msg"
    - "/t"
    - "/tell"
    - "/w"
    - "/whisper"

# Настройка автосообщений
autoMessage:
  # Включён ли autoMessage
  enable: true
  # Отправлять ли сообщения случайным образом
  random: true
  # Интервал между сообщениями в секундах
  messageInterval: 300
  # Сообщения
  # Можно указывать любые ID
  # Поддерживаются hoverText и clickEvent:
  # hoverText={текст при наведении}
  # clickEvent={тип_действия;значение}
  # Доступные действия:
  # https://hub.spigotmc.org/jenkins/job/BungeeCord/ws/chat/target/apidocs/net/md_5/bungee/api/chat/ClickEvent.Action.html
  # Также поддерживаются кнопки:
  # button={текст;hoverText;clickEvent}
  messages:
    1:
      - "[PromisedChat] &aПервое авто-сообщение"
    2:
      - "[PromisedChat] &bВторое авто-сообщение, строка 1"
      - "[PromisedChat] &bВторое авто-сообщение, строка 2"
    3:
      - "[PromisedChat] &cТретье авто-сообщение с hover-текстом hoverText={Тот самый текст}"
      - "[PromisedChat] &cТретье авто-сообщение с click-событием clickEvent={SUGGEST_COMMAND;/say Я нажал на автосообщение в чате!}"

# Плейсхолдеры плагина
placeholders:
  time:
    hours: ' ч. '
    minutes: ' мин. '
    seconds: ' сек. '